"""change whatsapp_link to text

Revision ID: f21a8f592e69
Revises: ac46f4e3f51d
Create Date: 2026-04-06 05:15:32.197535
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f21a8f592e69'
down_revision: Union[str, None] = 'ac46f4e3f51d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outreach_messages', 'whatsapp_link',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outreach_messages', 'whatsapp_link',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
